add loading end errors pages
14-team-6/FightClub pull request #12
Opened 2022-06-01 23:14 UTC by s-ratashnyuk

2022-06-02 11:48 UTC, kayun requested changes

2022-06-02 11:48 UTC, kayun commented on frontend/src/pages/errors/errors.tsx
> +type ErrorProps = {
Это должен быть интерфейс, чтобы его можно было унаследовать, в случае необходимости.

2022-06-02 11:48 UTC, kayun commented on frontend/src/pages/game/loading/loading.tsx
> +      -webkit-text-stroke: 1px #fff500;
А это где-нибудь кроме webkit будет работать? Проверял?

2022-06-02 11:48 UTC, kayun commented on frontend/src/pages/errors/errors.tsx
> +  @font-face {
А почему глобальные стили в конкретном компоненте лежат и дублируются? @font-face подключается один раз глобально в одном месте, в корне приложения. Лучше все глобальные стили вынести в один файл и потом импортировать в frontend/src/index.tsx.

2022-06-02 11:48 UTC, kayun commented on frontend/src/pages/game/loading/loading.tsx
> +  line-height: 100vh;
А для чего тут ширина строки во весь экран? Не проще сделать высоту стоки обычную, и отцентровать блок с текстом?

2022-06-02 11:48 UTC, kayun commented on frontend/src/pages/game/loading/loading.tsx
> +    <Wrap/>
В компоненте ошибки Wrap это обертка для контента БЕЗ глобальных стилей, в этом просто глобальные стили. Две одинаковые станицы с одинаковым лэйаутом сверстаны по разному. Было бы не плохо сделать лэйаут один раз в отдельном компоненте и потом использовать его на всех станицах меня контент.

2022-06-02 17:28 UTC, s-ratashnyuk commented on frontend/src/pages/errors/errors.tsx
> +type ErrorProps = {
поменял на интерфейс

2022-06-02 17:29 UTC, s-ratashnyuk commented on frontend/src/pages/errors/errors.tsx
> +  @font-face {
вынес глобальные стили отовсюду и добавил только в index.tsx

2022-06-02 17:29 UTC, s-ratashnyuk commented on frontend/src/pages/game/loading/loading.tsx
> +    <Wrap/>
привел к единому стилю + вынес в компонент то, что повторялось

2022-06-02 17:29 UTC, s-ratashnyuk commented on frontend/src/pages/game/loading/loading.tsx
> +  line-height: 100vh;
Убрал, сделал на флексе

2022-06-02 17:31 UTC, s-ratashnyuk commented on frontend/src/components/strokedText/strokedText.tsx
> +      const newWidth = (Number(fontSize) / 2.1538) * textWidth;
для именно этого шрифта такая "математика" годится

2022-06-05 15:36 UTC, s-ratashnyuk commented on frontend/src/pages/game/loading/loading.tsx
> +      -webkit-text-stroke: 1px #fff500;
сделал на text-shadow, взял из ПРа Андрея. (на свг тоже переделал и даже получилось, но ради унификации поменял)

2022-06-06 07:42 UTC, kayun approved these changes

2022-06-06 08:59 UTC, s-ratashnyuk commented on frontend/src/pages/errors/errors.tsx
> +  -webkit-text-stroke: 4px #fff500;
уже вынес ) взял из ПРа Андрея

2022-06-06 09:02 UTC, KrylovaOka approved these changes

2022-06-06 09:23 UTC, merged