5. add login and register pages
14-team-6/FightClub pull request #13
Opened 2022-06-02 16:46 UTC by andrei-daniloff

2022-06-02 23:33 UTC, s-ratashnyuk requested changes

2022-06-02 23:33 UTC, s-ratashnyuk commented on frontend/src/components/input/input.tsx
> +  font-family: ${PIXEBOY};
ты не хочешь вынести подключение шрифта в базовый стиль (например в mainlayout), чтобы не подключать его в каждом компоненте? Шрифт во всем проекте один.

2022-06-02 23:33 UTC, s-ratashnyuk commented on frontend/src/components/input/input.tsx
> +      {error && <Span>{error.message}</Span>}
как писал в чатике, из-за этого перерисовывается страница
вот так {<Span>{error?.message}</Span>} - не будет перерисовываться

2022-06-03 03:54 UTC, andrei-daniloff commented on frontend/src/components/input/input.tsx
> +  font-family: ${PIXEBOY};
да, мувнул в глобал

2022-06-03 11:05 UTC, andrei-daniloff commented
да, ховер добавил
![image](https://user-images.githubusercontent.com/33805592/171842166-881dc162-760d-437d-beb4-6f153baeffe7.png)
![image](https://user-images.githubusercontent.com/33805592/171842198-0b0398fb-d6ba-4423-b728-bb28da9b8288.png)

2022-06-03 14:44 UTC, s-ratashnyuk approved these changes

2022-06-06 07:44 UTC, kayun approved these changes

2022-06-06 08:15 UTC, merged