12.add canvas
14-team-6/FightClub pull request #15
Opened 2022-06-06 08:34 UTC by KrylovaOka

Коты ходят пока на странице /fight
Сделано
1. Модуль, который слушает клавиатуру
2. Компонент canvas
3. Класс character - это непосредственно сам персонаж - кот

Один кот управляется с клавиатуры: a - назад, d - вперед, w- прыжок
Второй кот типа искусственный интеллект, но сейчас он пока не слишком интеллектуально просто ходит туда-сюда и даже может в какой-то момент и вовсе уйти из кадра.

2022-06-07 12:08 UTC, andrei-daniloff commented
заметил недостаток в управлении - если зажать прыжок, то кот бесконечно летит вверх)
![image](https://user-images.githubusercontent.com/33805592/172375140-60e4176b-8dd9-4b8b-a10c-86f3f80fb85e.png)

2022-06-08 07:40 UTC, KrylovaOka commented
> 

С прыжком, насколько я помню, в подобных играх персонажи так себя и вели, летели вверх, пока зажата кнопка. Но это не точно ) Хочется, чтобы высота прыжка зависела от длительности зажатия кнопки. Но, наверное, нужен какой-то другой предел, а не верхняя граница экрана.
Предлагаю обсудить этот вопрос с командой, какой должна быть логика прыжка.

По поводу ИИ я сильно не заморачивалась, т.к. это пока функция-заглушка, он все равно будет вести себя как-то иначе на самом деле.

2022-06-08 09:47 UTC, s-ratashnyuk commented
Прыжок на мой взгляд должен работать так:
1. определяем направление движения
2. если котик двигается, прыжок делается по дуге (что-то вроде y = -0.7*x^2). Если котик стоит - прыжок делается вверх
3. когда прыжок начался, нельзя повлиять на направление движения
4. если в прыжке нажать "вправо-влево", котик может перевернуться (так, чтобы после приземления "смотреть" в нужную игроку сторону)
5. движение по дуге происходит с "изингом" - начинается быстро, к верхней точке замедляется, к концу дуги снова ускоряется

2022-06-08 09:52 UTC, KrylovaOka commented
> Прыжок на мой взгляд должен работать так:
> 
> 1. определяем направление движения
> 2. если котик двигается, прыжок делается по дуге (что-то вроде y = -0.7*x^2). Если котик стоит - прыжок делается вверх
> 3. когда прыжок начался, нельзя повлиять на направление движения
> 4. если в прыжке нажать "вправо-влево", котик может перевернуться (так, чтобы после приземления "смотреть" в нужную игроку сторону)

А по высоте прыжка как бы предложил организовать ограничение?

> 5. движение по дуге происходит с "изингом" - начинается быстро, к верхней точке замедляется, к концу дуги снова ускоряется
думаю это должно быть в любом случае, не только по дуге

2022-06-08 11:23 UTC, KrylovaOka commented
> Я бы добавил тут небольшой рандом "для интереса". Чтобы сложнее было предсказать, где окажется котик.

Не соглашусь. Думаю в управлении должна быть какая-то логическая предсказуемость, чтобы вероятность выигрыша зависела от действий игрока.
 
> В будущем можно было бы сделать зависимость прыжка от длительности нажатия на кнопку. Не хочу предлагать делать это сейчас, потому что надо будет и ИИ как-то этому учить, а это сложно.

Он уже сейчас зависит от длительности нажатия. Но очень "в лоб" - пока держишь кнопку, высота увеличивается, отпускаешь - начинает снижаться. Т.е. получается, чем дольше нажатие, тем выше прыгнет.
В будущем - ты имеешь ввиду как вариант развития или просто не в этой задаче?

2022-06-08 11:37 UTC, s-ratashnyuk commented
> Он уже сейчас зависит от длительности нажатия. Но очень "в лоб"

Высота должна быть в любом случае не больше "х", и не должно меняться направление. То есть грубо говоря
- держу кнопку 100мс - высота у
- держу кнопку 200мс - высота у+10
- держу кнопку 300+мс - высота у+20 === х ( и больше не растет, сколько не держи кнопку)

> в управлении должна быть какая-то логическая предсказуемость, чтобы вероятность выигрыша зависела от действий игрока

это же не шахматы :) В таких играх всегда есть влияние случая, это делает игру разнообразнее и удерживает игрока

2022-06-11 12:51 UTC, andrei-daniloff approved these changes
Управление кота работает, остальное думаю в процессе дофикситься\доделается.

2022-06-14 13:12 UTC, kayun requested changes
Использовать ! для того чтобы тайпскрипт не ругался плохая затея. Нужно явно обрабатывать кейсы когда значения может не быть.

2022-06-18 09:13 UTC, KrylovaOka commented on frontend/src/components/canvas/canvas.tsx
> +    hero.current!.move(dt, keys);
Потому что герой управляется юзером, а остальные ИИ. Сейчас функция update просто заглушка, чтобы второй кот как-то двигался. Этот функционал еще надо разрабатывать по-нормальному.

2022-06-20 10:26 UTC, kayun commented on frontend/src/components/canvas/canvas.tsx
> +    hero.current!.move(dt, keys);
Ок, тогда нужно будет в дальнейшем на это обратить внимание.

2022-06-20 10:27 UTC, kayun approved these changes

2022-06-20 11:41 UTC, KrylovaOka commented on frontend/src/components/canvas/canvas.tsx
> +      characters.current[i].collision([hero.current!]);
Это я решила пока отложить, т.к. пока не понятно, как это будет использоваться, и будет ли вообще. Лучше сейчас не буду тратить время, если понадобится, исправим в других задачах.

2022-06-20 21:03 UTC, merged