8. add http transport and auth service
14-team-6/FightClub pull request #18
Opened 2022-06-07 05:54 UTC by andrei-daniloff

2022-06-08 07:34 UTC, KrylovaOka commented on frontend/core/http-transport.ts
> +            .catch(() => { return resolve(null); });
В третьем спринте был пример этого запроса, там анализировали заголовки.
Вот так:
    fetch(`${process.env.API_ENDPOINT}/${path}`, {
      method,
      credentials: 'include',
      mode: 'cors',
      headers: { 'Content-Type': 'application/json' },
      body: data ? JSON.stringify(data) : null,
    })
      .then((response) => {
        const isJson = response.headers
          .get('content-type')
          ?.includes('application/json');
        return isJson ? response.json() : null;
      })
Не знаю, насколько это бест, но как вариант

2022-06-12 09:11 UTC, andrei-daniloff commented on frontend/core/http-transport.ts
> +            .catch(() => { return resolve(null); });
Да, как вариант. Но вот чисто из интереса - может прийти битый json, при обработке которого вылетит эксепшн?

2022-06-14 09:34 UTC, kayun requested changes

2022-06-14 09:34 UTC, kayun commented on frontend/core/http-transport.ts
> +            .catch(() => { return resolve(null); });
Тут можно предложить вот какую схему.

У нас есть несколько методов для получения тела ответа. Два основных это получить как тект и как json. Если разные эндпоинты возвращают разный формат(что не есть хорошо и это проблема бэкенда), то мы можем в Options методов транспорта добавить еще один, который будут решать какой формат вернуть.
Что-то типо вот такого:
```
type ResponseHandler = <T>(response: Response) => Promise<T>


```
Это более гибкое решение чем вам предлагали раньше, так как для каждого конкретного запроса мы сами можем решать как его обработать. Например если при логине возвращается строка, то наша функция будет выглядеть вот так `(response: Response) => response.text()`
Тогда метод логина будет выглядить вот так
```
public signIn = (userInfo: LoginFormData) => {
    return this.authService
      .post<LoginFormData>('/signin', {
           body: userInfo,
           handler: <string>(response: Response) => response.text()
       })
       .then(text => {success: text === 'OK'});
  };
```
Тогда все методы будут возвращать json это лучше если бы кадлый метод возвращал разные форматы.

2022-06-14 09:34 UTC, kayun commented on frontend/core/http-transport.ts
> +            .catch(() => { return resolve(null); });
Если придет невалидный json, то его так же можно будет обработать в handler.

2022-06-14 09:34 UTC, kayun commented on frontend/core/http-transport.ts
> +          response.json()
Учитывая коммент про разные форматы(ниже) тут мы не будем вызывать какой-то конкретный метод для получения боди, а просто достанем handler и передадим в него респонс.

```
if (response.ok) {
    return handler(response)
} else {
    throw new HttpError(`Ошибка HTTP соединения, статус - ${response.status}`)
}
```
Тут важное замечание если response.ok возвращает false, то мы не можем получить тело и вызов - запрос не прошел. Поэтому нужно выбрасывать исключение. Тут я привел пример кастомной ошибки, так проще будет проверять что это ошибка http соединения, но можно использовать просто Error.

2022-06-14 09:34 UTC, kayun commented on frontend/core/http-transport.ts
> +          response.json()
Чтобы каждый раз в Options не передавать handler будем считать, что по умолчанию у нас все эндпоинты отдают json и тогда можем сделать для handler значение по дефолту - `(response: Response) => response.json()`

2022-06-14 09:34 UTC, kayun commented on frontend/core/http-transport-abstract-class.ts
> +  abstract delete<T>(url: string, options: Options<T>): Promise<any>;
options: Options<T> = {} - чтобы не передавать в метод пустой объект если никаких опций мы не передаем.

2022-06-14 09:34 UTC, kayun commented on frontend/core/http-transport.ts
> +  public get = (url: string, options: Options<any> = {}): Promise<any> => {
А для чего тут поля вместо методов?
Если задать это методами, то они будут храниться в прототипе, а если полями, то у каждого инстанса транспорта будут эти функции - памяти больше тратится в таком случае.

2022-06-14 09:34 UTC, kayun commented on frontend/src/components/registerPageForm/registerPageForm.tsx
>  const schema = yup.object({
Тут схему тоже в одельный файл.

2022-06-19 10:35 UTC, andrei-daniloff commented
Вроде все поправил, ничего не пропустил.

2022-06-20 10:25 UTC, kayun approved these changes

2022-06-20 10:25 UTC, kayun commented
Огонь!

2022-06-20 12:37 UTC, merged