7.result page
14-team-6/FightClub pull request #20
Opened 2022-06-08 16:41 UTC by s-ratashnyuk

2022-06-12 09:08 UTC, andrei-daniloff commented on frontend/src/components/button/buttonTriangle.tsx
> +  const classNames = [];
Предлагаю сделать useMemo и перенести туда всю логику по простановке классов. Во втором аргументе useMemo добавить массив с параметрами, от которых зависит логика по сеттингу классов.
Так будет инкапсулирована логика + мемоизирована, т.к. сейчас у тебя на каждый перерендер компонента создается массив и прогоняется логика по сеттингу классов. И нужно сам компонент обернуть в React.memo, чтобы перерендер не триггерился на те же самые пропсы.

2022-06-12 09:08 UTC, andrei-daniloff commented on frontend/src/components/button/buttonTriangle.tsx
> +  });
Давай сюда еще добавим вторым аргументом isActive, чтобы useEffect триггерился при инициализации компонента и при обновлении пропсы isActive.

2022-06-12 09:08 UTC, andrei-daniloff commented on frontend/src/pages/results/components/leaders.tsx
> +          {props.items.map((o, i) => {
Трудно понять что такое "o". Поменяй плиз на более понятное имя + можно тип указать. И использовать индекс элемента в качестве ключа не очень хорошая идея. [дока](https://ru.reactjs.org/docs/lists-and-keys.html#:~:text=%D0%9C%D1%8B%C2%A0%D0%BD%D0%B5%C2%A0%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D0%BC%20%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D0%B8%D0%BD%D0%B4%D0%B5%D0%BA%D1%81%D1%8B%20%D0%BA%D0%B0%D0%BA%20%D0%BA%D0%BB%D1%8E%D1%87%D0%B8%2C%20%D0%B5%D1%81%D0%BB%D0%B8%20%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA%20%D1%8D%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D0%BF%D0%BE%D0%BC%D0%B5%D0%BD%D1%8F%D1%82%D1%8C%D1%81%D1%8F.)

2022-06-12 09:08 UTC, andrei-daniloff commented on frontend/src/components/button/buttonTriangle.tsx
> +    background: url("../../../public/img/buttonArrow-blue.svg");
Если вдруг поменяем директорию для пикчи, IDE хотя бы сама импорты поправит, а вот насчет урлы в стилях - не уверен.

2022-06-12 09:14 UTC, andrei-daniloff commented on frontend/src/pages/results/components/leaders.tsx
> +          {props.items.map((o, i) => {
И у тебя в этом файле много компонентов, может их раскидать по отдельным файликам?

2022-06-12 14:03 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +  general,
сделал

2022-06-12 14:04 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +    background: url("../../../public/img/buttonArrow-blue.svg");
сделал

2022-06-12 14:04 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +  const classNames = [];
сделал

2022-06-12 15:31 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +  });
готово

2022-06-12 15:31 UTC, s-ratashnyuk commented on frontend/src/pages/results/components/leaders.tsx
> +          {props.items.map((o, i) => {
поменял и раскидал

2022-06-12 22:03 UTC, andrei-daniloff commented on frontend/src/pages/results/results.tsx
> +  background: url("../../../public/img/Meow-Knight_Attack_2.png") 0 ${(props: KittenProps) => {
А давай тут тоже на константу поменяем.

2022-06-13 00:26 UTC, s-ratashnyuk commented on frontend/src/pages/results/results.tsx
> +  background: url("../../../public/img/Meow-Knight_Attack_2.png") 0 ${(props: KittenProps) => {
готово

2022-06-13 05:58 UTC, andrei-daniloff approved these changes

2022-06-14 10:35 UTC, kayun requested changes
Пока вижу проблемы со стилизацией, нужно почитать доку по styled-components и использовать примеры оттуда.

2022-06-14 10:35 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +const GC = createGlobalStyle`
Эти стили объявятся как глобальные и во всем приложении будет доступен класс .small. styled-components придумали именно для того чтобы изолировать стили компонентов, поэтому внутри компонентов не может быть глобальных стилей.

В базовой документации по styled-components про это написано - https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting

2022-06-14 10:35 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +  UP = 'UP',
Почему тут заданы значения для перечислений, а ниже не заданы? Хотя используются они совершенно одинаковым образом.

2022-06-14 10:35 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +  const [active, setActive] = useState<Boolean>(false);
У этого компонента нет внутреннего состояния. Направление триугольника задается только через props'ы. Этот компонент - чистая функция, отображение зависит только от входных параметром и при изменении параметров каждый раз перерендеривается.

Соответственно и useEffect тут не нужен.

2022-06-14 10:35 UTC, kayun commented on frontend/src/components/scrollBlock/scrollBlock.tsx
> +      console.log(`direction: ${direction}`);
Для чего тут обработчик, если он ничего не делает? Тут наверное должна быть логика того как скролится блок будет?

В зависимости от этой логики в ButtonTriangle в isActive будут передавать разные значения и от этого будет меняться цвет.

2022-06-14 10:35 UTC, kayun commented on frontend/src/pages/results/components/leaderListItem.tsx
> +import { MAIN_RED, MAIN_YELLOW } from '../../../../consts/styles';
Неплохо бы было в вебпаке настроить алиасы для того чтобы писать импорты вот так - `import { MAIN_RED, MAIN_YELLOW } from 'consts/styles';`, то есть от корня, а не 100500 подъемов по папкам.

Кстати почему папка называется consts, а не нормально - constants?) Экономия в 3 символа?)

2022-06-14 10:35 UTC, kayun commented on frontend/src/pages/results/components/leaderListItem.tsx
> +  .stroked-text {
Нужно расширять компоненты, а не css каскад использовать - https://styled-components.com/docs/basics#styling-any-component

Наверное вообще надо почитать доку по styled-components повнимательней).

2022-06-14 10:35 UTC, kayun commented on frontend/src/pages/results/components/sortBlock.tsx
> +  .button-triangle:first-child {
Стилизовать через наследование.

2022-06-14 10:35 UTC, kayun commented on frontend/src/pages/results/components/sortBlock.tsx
> +const SortBlockImpl: FC = () => {
ScrollBlock точно такой же компонент с отличающимися стилями. Нужно написать один универсальный компонент-контейнер для триуголных листалок. Нужно предусмотреть, что скролл может быть как по вертикали, так и по горизонтале.

2022-06-14 10:35 UTC, kayun commented on frontend/src/pages/results/results.tsx
> +  margin: calc(100vh / 2 - 200px) 0 0;
200px - магическое число, никто не понимает что оно означает и почему 200. Нужно вынести в константу и назвать правильно.

2022-06-14 10:35 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +  const classNames = useMemo(() => {
Для таких задач, когда нужно добавлять несколько классов по условию нужно использовать библиотеку classname.

2022-06-14 16:35 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +    transform: scale(0.58);
убрал свг, перешел на css. Оставил transform только для переворота треугольника, чтобы не дублировать правила. Это ок?

2022-06-14 16:35 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +const GC = createGlobalStyle`
убрал

2022-06-14 16:35 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +  const [active, setActive] = useState<Boolean>(false);
убрал

2022-06-14 16:36 UTC, s-ratashnyuk commented on frontend/src/components/scrollBlock/scrollBlock.tsx
> +      console.log(`direction: ${direction}`);
в будущем тут будет отправляться событие для изменения порядка сортировки / скролла

2022-06-14 16:36 UTC, s-ratashnyuk commented on frontend/src/pages/results/components/leaderListItem.tsx
> +  .stroked-text {
готово

2022-06-14 16:36 UTC, s-ratashnyuk commented on frontend/src/pages/results/components/sortBlock.tsx
> +  .button-triangle:first-child {
готово

2022-06-14 16:36 UTC, s-ratashnyuk commented on frontend/src/pages/results/results.tsx
> +  margin: calc(100vh / 2 - 200px) 0 0;
убрал, переназвал

2022-06-14 16:36 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +  const classNames = useMemo(() => {
внедрил

2022-06-15 07:56 UTC, kayun commented on frontend/src/pages/results/components/sortBlock.tsx
> +const SortBlockImpl: FC = () => {
В таком случае пусть будут разные, просто выглядели они как одно и то же. Но если функционал различается координально, то не надо в один компонент сливать.

2022-06-15 08:31 UTC, kayun requested changes
В целом ок, но нужно поправить общий стиль работы с пропсами и алиасы более читаемыми сделать.

2022-06-15 08:31 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +import classNamesBuild from 'classnames';
Обычно называют `cx` когда импортируют classnames, так повелось).

2022-06-15 08:31 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +      <ButtonTriangleStyled onClick={props.onClick} isActive={props.isActive}
Лучше делать вот так
```
const {onClick, isActive} = props;
```
А еще лучше деструктурировать в самой функции
```
const ButtonTriangleImpl:FC<ButtonTriangleProps> = ({onClick, isActive}) =>
```

2022-06-15 14:06 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
>                                   className={`${props.className} ${classNames}`}/>
поправил, спасибо!

2022-06-15 14:08 UTC, s-ratashnyuk commented on frontend/src/pages/results/components/sortBlock.tsx
> +  .button-triangle:first-child {
хм, padding не сработал - я хочу "раздвинуть" эти элементы, чтобы они совпадали с линией текста. И для этого у каждого элемента добавляю отступы.

кажется, понял, как надо делать с наследованием (и поправил)

2022-06-15 14:08 UTC, s-ratashnyuk commented on frontend/src/components/scrollBlock/scrollBlock.tsx
> +import { ButtonTriangle, ButtonTriangleDirection, ButtonTriangleSize } from '@fcomponents/button/buttonTriangle';
исправил / поправил

2022-06-15 14:08 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +import classNamesBuild from 'classnames';
поменял

2022-06-15 14:12 UTC, s-ratashnyuk commented on frontend/src/components/button/buttonTriangle.tsx
> +      <ButtonTriangleStyled onClick={props.onClick} isActive={props.isActive}
тут деструктурировал в самой функции, тк - на мой взгляд - это более читабельно (много свойств)
в других местах переделал на деструктурирование в определении функции

2022-06-15 14:23 UTC, kayun commented on frontend/src/components/button/buttonTriangle.tsx
> +      <ButtonTriangleStyled onClick={props.onClick} isActive={props.isActive}
Ок. Но совершенно нормально когда пишешь вот так, в больших проектах так повсеместно делают(23-30 пропсов это нормально.)
```
const ButtonTriangleImpl:FC<ButtonTriangleProps> = ({
    onClick,
    isActive,
    other1,
    other2,
    other2,
    other2,
    other2,
    other2,
    other2
}) => {
    // тело функции
}
```

2022-06-15 14:36 UTC, merged