21. add sound
14-team-6/FightClub pull request #22
Opened 2022-06-15 15:23 UTC by s-ratashnyuk

чтобы услышать звук, надо перейти по ссылке Sound check с главной страницы. Иначе ничего работать не будет из-за правил безопасности в браузерах

2022-06-16 12:35 UTC, kayun requested changes

2022-06-16 12:35 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +export class Sounds {
А что это за класс такой который только из статических членов состоит?)
Ты хотел сделать класс который доступен во всем приложении в одном экземпляре? Если так, то тебе нужно использовать паттерн синглтон - он как раз для этих целей.

Вот тут есть описание и пример на TS - https://refactoring.guru/ru/design-patterns/singleton

2022-06-16 12:35 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +  private static getBufferFromUrl(url: string) {
Типы для возвращаемых значений тоже нужно определять явно.

2022-06-16 12:35 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +        // using only audioContext cause to
Если копируешь код откуда-то, то хотя бы вычищай лишнее).

2022-06-16 12:35 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +        const offlineContext = new OfflineAudioContext(2, 44100 * audioBuffer.duration, 44100);
Частоту дескритизации в константу нужно вынести. Магическое число, опять же.

2022-06-16 12:35 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +    return fetch(url)
Можно использовать async/await. Но это по желанию.

2022-06-16 12:35 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +      throw Error('Could not load main theme');
Тут если файл не подгрузился ляжет все приложение, нужно обрабатывать эту ошибку, например писать в консоль что все плохо и просто не проигрывать звук.

2022-06-16 12:35 UTC, kayun commented on frontend/src/pages/game/stub.tsx
> +import React, { FC, useCallback, useEffect } from 'react';
А можно это добавить на станицу с началом поединка? Чтобы не плодить кучу станиц.
В меню браузер не даст проигрывать музыку пока пользователь не совершит каких-нибудь действий, а при переходе на станицу игры должно все заработать.

2022-06-16 12:36 UTC, s-ratashnyuk commented on frontend/src/game/components/sounds/sounds.ts
> +        // using only audioContext cause to
весь код написан мной с нуля ) а что там лишнее?

2022-06-16 12:37 UTC, s-ratashnyuk commented on frontend/src/pages/game/stub.tsx
> +import React, { FC, useCallback, useEffect } from 'react';
это заглушка только чтобы потестить, я уберу, когда вольется канвас и можно будет в него залезть

2022-06-16 12:38 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +        // using only audioContext cause to
Аааа, понял. Просто комменты ты до этого не писал)). Вот я и насторожился.

2022-06-16 12:40 UTC, s-ratashnyuk commented on frontend/src/game/components/sounds/sounds.ts
> +export class Sounds {
мне показалось, что тут именно статичные методы лучше использовать, потому что создавать экземпляр класса, где не будет никакой "кастомизации" (то есть везде всегда будут одни и те же звуки итд) странно. Так делать не принято и правильнее использовать синглтон?

2022-06-16 13:03 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +export class Sounds {
Есть отдельные случаи когда можно использовать класс состоящий только из статичных методов, но как правило эти методы все публичные и каждый выполняет какую-то одну функию. Ну например класс Util где собраны всякие вспомогательные методы.

У тебя же класс методы и поля которого взаимодействую между собой, поэтому это обычный класс в единственном экземпляре.

**Задание со звездочкой)**
Вообще если упороться, то можно сделать один небольшой класс который принимает звуковой файл, подгружает его и умеет только запускать и останавливать проигрывание.
Дальше завести фабрику у которой будет метод создания этого класса. В него будет передаваться файл, а возвращать метод будет уже готовый класс. Плюс чтобы на каждый класс не создавать новый аудио контекст можно в фабрике создать один контекст и его передавать во все классы которые занимаются воспроизведением. ВОт тут про фабрику - https://refactoring.guru/ru/design-patterns/factory-method
И наконец чтобы все это собрать вместе можно все эти классы обернуть фасадом у которого будут публичные методы нужные для проекта. Например async init() который будет асинхронно создавать все классы(по одному на файл), а дальше те методы которые непосредственно будут вызываться при действиях пользователя. Эти методы будут переадресовывать работу классам с файлами и такая структура будет достаточно гибкой. Чтобы добавить новый звук нужно будет добавить файл и новый метод в фасад. ВОт тут про фасад - https://refactoring.guru/ru/design-patterns/facade

Это если хочется разобраться с паттернами немножно, не обязательно.

2022-06-16 13:05 UTC, kayun commented on frontend/src/game/components/sounds/sounds.ts
> +export class Sounds {
Либо оставить синглтон со всеми методами нужными. Но он у тебя может разрастись со временем, если будут добавляться новые звуки.

2022-06-17 13:57 UTC, s-ratashnyuk commented on frontend/src/game/components/sounds/sounds.ts
> +export class Sounds {
готово

2022-06-17 14:00 UTC, s-ratashnyuk commented on frontend/src/game/components/sounds/sounds.ts
> +      throw Error('Could not load main theme');
сделал. теперь приложение не упадет (но не стартанет весь звук)
имхо это правильно - сразу будет понятно, что где-то есть проблема. А если игнорировать только тот звук, где случилась ошибка и не загрузится только, например, третий вариант озвучки атаки, это пройдет незамеченным

2022-06-18 08:31 UTC, KrylovaOka approved these changes

2022-06-20 10:24 UTC, kayun approved these changes

2022-06-20 10:42 UTC, merged