4.main page
14-team-6/FightClub pull request #23
Opened 2022-06-17 18:26 UTC by KrylovaOka

Вынесла декоративный элемент с котиками в отдельный компонент, из-за этого пришлось внести изменения в страницу results

2022-06-17 22:56 UTC, s-ratashnyuk requested changes

2022-06-17 22:56 UTC, s-ratashnyuk commented on frontend/consts/styles.ts
> +export const KITTEN_WIDTH: number = 160;
странно, почему линтер это пропустил - нет пустой строки в конце файла

2022-06-17 22:56 UTC, s-ratashnyuk commented on frontend/src/pages/main/main.tsx
> +            <Kitten direction="right" sprite={1} width={KITTEN_WIDTH} height={KITTEN_HEIGHT} className="kitten left" />
у котиков одинаковые размеры на всех страницах, не хочешь это вынести в компонент Kitten? (я про width и height)

2022-06-17 22:56 UTC, s-ratashnyuk commented on frontend/src/pages/main/main.tsx
> +            <NavItem><StyledLink to="/game/loading">Start</StyledLink></NavItem>
предлагаю
- сделать компонент "список" (он пригодится еще на нескольких страницах)
- использовать внутри списка везде либо линки, либо кнопки (кажется, если подходящая кнопка в компонентах)

2022-06-18 07:29 UTC, KrylovaOka commented on frontend/src/pages/main/main.tsx
> +            <Kitten direction="right" sprite={1} width={KITTEN_WIDTH} height={KITTEN_HEIGHT} className="kitten left" />
Ну а вдруг мы где-то захотим кота в другом размере? мне кажется, удобно задавать размер в пропсах.

2022-06-18 07:39 UTC, KrylovaOka commented on frontend/src/pages/main/main.tsx
> +            <NavItem><StyledLink to="/game/loading">Start</StyledLink></NavItem>
По п.1 можно и вынести. А где он еще может пригодиться? У нас и страниц-то вроде больше не будет.

По п.2 я руководствовалась такой логикой: линки - это элемент для навигации, странно использовать в этих целях кнопку, надо будет вешать на нее обработчик для перехода на другую страницу, зачем, если есть предусмотренный для этого элемент? А кнопка - это элемент для вызова какого-то действия, в данном случае для разлогинивания. Это не переход на другую страницу. Разные по сути элементы в разных компонентах.
Другой разговор, что выглядят они одинаково. Но это может быть и не так в другом оформлении.
В общем считаю правильным отталкиваться от функционального назначения, а не от внешнего вида при выборе компонента.
То, что в одном списке разные элементы и правда не очень. Давай вынесем кнопку за пределы списка )

2022-06-18 08:08 UTC, KrylovaOka commented on frontend/consts/styles.ts
> +export const KITTEN_WIDTH: number = 160;
Исправила. Линтер и правда странно работает. У меня он ругался на файлы, которые я взяла с сервера, которые уже проверялись у других и были пропущены

2022-06-18 10:17 UTC, s-ratashnyuk commented on frontend/src/pages/main/main.tsx
> +            <NavItem><StyledLink to="/game/loading">Start</StyledLink></NavItem>
п. 1 - например, "настройки", "стартовая страница" (где логин / регистер), страницы окончания игры

2022-06-18 11:07 UTC, KrylovaOka commented on frontend/src/pages/main/main.tsx
> +            <NavItem><StyledLink to="/game/loading">Start</StyledLink></NavItem>
вынесла отдельно

2022-06-19 07:08 UTC, s-ratashnyuk commented on frontend/src/pages/main/main.tsx
> +            <NavItem><StyledLink to="/game/loading">Start</StyledLink></NavItem>
я имел в виду сделать компонент, куда передаем массив объектов (название, id), а он рисует меню
@kayun Артем, а как правильнее в такой ситуации?

+ еще есть визуальные проблемки, но как я понял, это по желанию ¯\_(ツ)_/¯  - расстояния между пунктами больше, чем в макете

2022-06-19 08:10 UTC, KrylovaOka commented on frontend/src/pages/main/main.tsx
> +            <NavItem><StyledLink to="/game/loading">Start</StyledLink></NavItem>
я не вижу смысла делать это. Это просто стилизованый список, у него нет и не будет никакой дополнительной функциональности, кроме как отображать список. А для отображения списка уже все все придумано в HTML.
По мне это деятельность ради деятельности.
Подождем мнения Артема ))
По поводу расстояния - ты же сам писал, что макет несовершенен и примерный. Если расстояние сделать меньше, текст тяжело читается, у нас еще и шрифт такой специфический, хочется немного хоть воздуха.

2022-06-19 13:53 UTC, s-ratashnyuk approved these changes

2022-06-21 04:41 UTC, merged