38. some fixes
14-team-6/FightClub pull request #36
Opened 2022-07-05 18:53 UTC by andrei-daniloff

2022-07-11 11:03 UTC, s-ratashnyuk requested changes
Давай добавим обработку ошибок? 
К самому ПРу у меня претензий кажется нет, но продуктово оно не работает :-)
Я запускаю дев сервер, попадаю на страницу логина, ввожу логин / пароль, получаю ошибку "пользователь уже в системе". И далее мне никуда не деться (кроме похода в девтулзы для удаления кук). 
Предлагаю два варианта:
- либо при попытке логина всегда делать перед этим логаут (невзирая на ошибки)
- либо парсить ответ от сервера, и если он говорит, что пользователь уже залогинен, обрабатывать это
- либо перед попыткой логина запрашивать данные о пользователе, если данные проходят - делать выводы, что пользователь залогинен

2022-07-14 06:16 UTC, andrei-daniloff commented
Добавил колл за юзером в хук и надо бы придумать лоадер, пока ждём ответ что чувак залогинен. И опять поймал проблему, как была с формами - при изменении стейта обновляется фулл страница (достаточно покликать в главном меню на страницы форума или лидеров), но потом работает как нужно ( вроде так и не узнали почему так случается). 
Еще обернул весь апп в майн лайаут, чтобы избежать моргания, при смене лоадера на чилду.

2022-07-14 06:17 UTC, andrei-daniloff commented
Конфликты поправлю asap

2022-07-15 10:29 UTC, s-ratashnyuk approved these changes

2022-07-16 11:04 UTC, merged