49. connect edit profile
14-team-6/FightClub pull request #58
Opened 2022-07-23 20:08 UTC by andrei-daniloff

2022-07-23 20:12 UTC, andrei-daniloff commented
Хотел еще аватар добавить, но походу посмотрел и думаю что тянет на отдельную таску.

2022-07-23 23:38 UTC, s-ratashnyuk requested changes

2022-07-23 23:38 UTC, s-ratashnyuk commented on frontend/src/reducers/user.ts
> +  id: 0,
из-за этого не сломается метод isCookieInvalid? (hooks/useAuth)

2022-07-24 12:37 UTC, andrei-daniloff commented on frontend/src/reducers/user.ts
> +  id: 0,
да, нолик не в тему. поправил

2022-07-24 13:00 UTC, s-ratashnyuk approved these changes

2022-07-24 13:00 UTC, merged