Themes frontend
14-team-6/FightClub pull request #65
Opened 2022-07-29 20:27 UTC by KrylovaOka

Красивую тему сделать запала не хватило, для примера сделала просто черно-белую.
В самой игре не все компоненты темизированы, надо будет позже доделать.
И запись с темой для БД сейчас коряво создается, множится при каждом перезапуске, надеюсь, кто-нибудь знает, как это сделать нормально и сделает )

2022-07-30 21:55 UTC, s-ratashnyuk requested changes

2022-07-30 21:55 UTC, s-ratashnyuk commented on backend/src/components/sequelizeGlobal.ts
> +        const themeData = {
я правильно понимаю, что ты после подключения к базе и проверки ее структуры, на каждый запуск сервера создаешь тему?

2022-07-30 21:55 UTC, s-ratashnyuk commented on backend/src/server/serverMiddleware.tsx
> +  if ('theme' in req.cookies) {
может в локал сторадж вместо куки?

2022-07-30 21:55 UTC, s-ratashnyuk commented on frontend/src/services/themeService.ts
> +      this.service.post('/linkToUser', {
я бы не звал это, если польз. не залогинен - бэк все равно не даст сохранить (и ругается в консоли)

2022-07-31 10:44 UTC, KrylovaOka commented on backend/src/components/sequelizeGlobal.ts
> +        const themeData = {
Да, правильно все понимаешь. Именно об этом я пишу в комментарии к PR. Понимаю, что так делать не надо, но не знаю, как надо )
Хочу подсказку коллективного разума

2022-07-31 10:44 UTC, KrylovaOka commented on backend/src/server/serverMiddleware.tsx
> +  if ('theme' in req.cookies) {
Здесь же на сервере дело происходит, нет доступа к локал сторадж

2022-07-31 10:46 UTC, KrylovaOka commented on frontend/src/services/themeService.ts
> +      this.service.post('/linkToUser', {
Да, ты прав, исправлю этот момент

2022-08-08 17:15 UTC, kxnkxv commented on backend/src/controllers/themes.ts
> +      res.send(JSON.stringify({}));
Не очень хорошая практика - возвращать пустой объект, лучше null

2022-08-08 17:18 UTC, kxnkxv approved these changes

2022-08-08 17:19 UTC, andrei-daniloff commented on frontend/src/app/app.tsx
> +            <Route path="/" element={<PublicRoutes/>}>
<Route path="/" element={<PublicRoutes/>} />

2022-08-08 17:19 UTC, andrei-daniloff commented on frontend/src/app/app.tsx
> +            </Route>
а этот лишний

2022-08-14 11:17 UTC, andrei-daniloff commented on frontend/src/pages/options/hooks/useThemes.ts
> +      const defaultTheme: ThemeItem = {
а зачем получаем список тем и потом еще докидываем дефолтную? её можно получить вместе с остальными?

2022-08-14 11:17 UTC, andrei-daniloff commented on frontend/src/services/themeService.ts
> +const transport: HttpTransport = new DefaultHttpTransport(THEMES_API_URL);
пихни плиз это в frontend/src/services/index.ts

2022-08-14 11:17 UTC, andrei-daniloff commented on package.json
> +    "build:utils": "cross-env NODE_ENV=production webpack --config build/webpack.utils.config.js",
а зачем эта команда? она нигде не вызывается.

2022-08-14 11:29 UTC, andrei-daniloff approved these changes

2022-08-16 19:57 UTC, merged